
-- -----------------------------------------------------
-- Schema bdVenda
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdVenda` DEFAULT CHARACTER SET utf8 ;
USE `bdVenda` ;

-- -----------------------------------------------------
-- Table `bdVenda`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdVenda`.`CLIENTE` (
  `CLIENTE_ID` INT NOT NULL AUTO_INCREMENT,
  `CLIENTE_TIPO` TINYINT NULL,
  `CLIENTE_IDENTIFICACAO` VARCHAR(20) NULL,
  `CLIENTE_NOME` VARCHAR(60) NULL,
  `CLIENTE_EMAIL` VARCHAR(60) NULL,
  `CLIENTE_TELEFONE` VARCHAR(9) NULL,
  `CLIENTE_ENDERECO_CIDADE` VARCHAR(45) NULL,
  `CLIENTE_ENDERECO_CEP` CHAR(8) NULL,
  `CLIENTE_ENDERECO_UF` CHAR(2) NULL,
  `CLIENTE_ENDERECO_RUA` VARCHAR(100) NULL,
  `CLIENTE_ENDERECO_BAIRRO` VARCHAR(45) NULL,
  `CLIENTE_ENDERECO_NUMERO` INT NULL,
  `CLIENTE_ENDERECO_COMPLEMENTO` VARCHAR(45) NULL,
  PRIMARY KEY (`CLIENTE_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdVenda`.`FORNECEDOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdVenda`.`FORNECEDOR` (
  `FORNECEDOR_ID` INT NOT NULL AUTO_INCREMENT,
  `FORNECEDOR_NOME` VARCHAR(60) NOT NULL,
  `FORNECEDOR_EMAIL` VARCHAR(60) NULL,
  `FORNECEDOR_NOME_FANTASIA` VARCHAR(45) NOT NULL,
  `FORNECEDOR_CNPJ` VARCHAR(14) NOT NULL,
  `FORNECEDOR_ENDERECO_CIDADE` VARCHAR(45) NULL,
  `FORNECEDOR_ENDERECO_CEP` CHAR(8) NOT NULL,
  `FORNECEDOR_ENDERECO_UF` CHAR(2) NULL,
  `FORNECEDOR_ENDERECO_RUA` VARCHAR(100) NULL,
  `FORNECEDOR_ENDERECO_BAIRRO` VARCHAR(45) NULL,
  `FORNECEDOR_ENDERECO_NUMERO` INT NULL,
  `FORNECEDOR_ENDERECO_COMPLEMENTO` VARCHAR(45) NULL,
  `FORNECEDOR_TELEFONE` VARCHAR(9) NULL,
  PRIMARY KEY (`FORNECEDOR_ID`),
  UNIQUE INDEX `FORNECEDOR_CNPJ_UNIQUE` (`FORNECEDOR_CNPJ` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdVenda`.`PRODUTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdVenda`.`PRODUTO` (
  `PRODUTO_ID` INT NOT NULL AUTO_INCREMENT,
  `PRODUTO_NOME` VARCHAR(60) NULL,
  `PRODUTO_DESCRICAO` VARCHAR(250) NULL,
  `PRODUTO_PRECO` DECIMAL(6,2) NULL,
  `PRODUTO_QUANTIDADE` INT NULL,
  `FORNECEDOR_ID` INT NOT NULL,
  PRIMARY KEY (`PRODUTO_ID`),
  INDEX `fk_PRODUTO_FORNECEDOR_idx` (`FORNECEDOR_ID` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUTO_FORNECEDOR`
    FOREIGN KEY (`FORNECEDOR_ID`)
    REFERENCES `bdVenda`.`FORNECEDOR` (`FORNECEDOR_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdVenda`.`NOTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdVenda`.`NOTA` (
  `NOTA_CODIGO` INT NOT NULL AUTO_INCREMENT,
  `NOTA_DATA` VARCHAR(20) NULL,
  `NOTA_QUANTIDADE` INT NULL,
  `CLIENTE_ID` INT NULL,
  `FORNECEDOR_ID` INT NULL,
  `PRODUTO_ID` INT NOT NULL,
  PRIMARY KEY (`NOTA_CODIGO`),
  INDEX `fk_NOTA_CLIENTE1_idx` (`CLIENTE_ID` ASC) VISIBLE,
  INDEX `fk_NOTA_FORNECEDOR1_idx` (`FORNECEDOR_ID` ASC) VISIBLE,
  INDEX `fk_NOTA_PRODUTO1_idx` (`PRODUTO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_NOTA_CLIENTE1`
    FOREIGN KEY (`CLIENTE_ID`)
    REFERENCES `bdVenda`.`CLIENTE` (`CLIENTE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NOTA_FORNECEDOR1`
    FOREIGN KEY (`FORNECEDOR_ID`)
    REFERENCES `bdVenda`.`FORNECEDOR` (`FORNECEDOR_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NOTA_PRODUTO1`
    FOREIGN KEY (`PRODUTO_ID`)
    REFERENCES `bdVenda`.`PRODUTO` (`PRODUTO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



INSERT INTO CLIENTE (CLIENTE_TIPO, CLIENTE_IDENTIFICACAO, CLIENTE_NOME, CLIENTE_EMAIL, CLIENTE_TELEFONE, CLIENTE_ENDERECO_CIDADE, CLIENTE_ENDERECO_CEP, CLIENTE_ENDERECO_UF, CLIENTE_ENDERECO_RUA, CLIENTE_ENDERECO_BAIRRO, CLIENTE_ENDERECO_NUMERO, CLIENTE_ENDERECO_COMPLEMENTO)
VALUES
(1, '12345678901', 'João Silva', 'joao@email.com', '119999999', 'São Paulo', '01001000', 'SP', 'Rua A', 'Centro', 100, 'Apto 1'),
(2, '98765432000199', 'Empresa XYZ', 'contato@xyz.com', '113333333', 'Santos', '11013000', 'SP', 'Av. B', 'Comercial', 200, 'Sala 5'),
(1, '11122233344', 'Maria Oliveira', 'maria@email.com', '119888888', 'Campinas', '13010000', 'SP', 'Rua C', 'Jardim', 150, NULL),
(1, '44455566677', 'Carlos Souza', 'carlos@email.com', '119777777', 'Ribeirão Preto', '14020000', 'SP', 'Rua D', 'Industrial', 300, 'Casa'),
(2, '11223344000155', 'Tech Ltda', 'suporte@tech.com', '114444444', 'Guarulhos', '07110000', 'SP', 'Av. E', 'Tecnológico', 400, 'Bloco B');


INSERT INTO FORNECEDOR (FORNECEDOR_NOME, FORNECEDOR_EMAIL, FORNECEDOR_NOME_FANTASIA, FORNECEDOR_CNPJ, FORNECEDOR_ENDERECO_CIDADE, FORNECEDOR_ENDERECO_CEP, FORNECEDOR_ENDERECO_UF, FORNECEDOR_ENDERECO_RUA, FORNECEDOR_ENDERECO_BAIRRO, FORNECEDOR_ENDERECO_NUMERO, FORNECEDOR_ENDERECO_COMPLEMENTO, FORNECEDOR_TELEFONE)
VALUES
('Distribuidora Alfa', 'alfa@fornecedores.com', 'Alfa', '12345678000190', 'São Paulo', '01002000', 'SP', 'Rua F', 'Comércio', 10, NULL, '113212345'),
('Comercial Beta', 'beta@fornecedores.com', 'Beta', '98765432000188', 'Campinas', '13020000', 'SP', 'Av. G', 'Centro', 20, 'Sala 2', '114545678'),
('Importadora Gama', 'gama@fornecedores.com', 'Gama', '11223344000177', 'Santos', '11020000', 'SP', 'Rua H', 'Portuário', 30, NULL, '115656789'),
('Tech Supply', 'tech@fornecedores.com', 'Tech', '22334455000166', 'São Bernardo', '09610000', 'SP', 'Av. I', 'Industrial', 40, 'Galpão 3', '116767890'),
('Logística Delta', 'delta@fornecedores.com', 'Delta', '33445566000155', 'Osasco', '06010000', 'SP', 'Rua J', 'Logística', 50, NULL, '117878901');


INSERT INTO PRODUTO (PRODUTO_NOME, PRODUTO_DESCRICAO, PRODUTO_PRECO, PRODUTO_QUANTIDADE, FORNECEDOR_ID)
VALUES
('Notebook X', 'Notebook com 16GB RAM e SSD 512GB', 3500.00, 10, 1),
('Mouse Óptico', 'Mouse com fio USB', 50.00, 100, 2),
('Monitor 24"', 'Monitor LED Full HD', 750.00, 25, 3),
('Teclado Mecânico', 'Teclado com switches azuis', 250.00, 40, 4),
('Impressora Laser', 'Impressora monocromática com Wi-Fi', 1200.00, 15, 5);


INSERT INTO NOTA (NOTA_DATA, NOTA_QUANTIDADE, CLIENTE_ID, FORNECEDOR_ID, PRODUTO_ID)
VALUES
('2025-10-01', 1, 1, null, 1),
('2025-10-02', 2, null, 2, 2),
('2025-10-03', 1, 3, null, 3),
('2025-10-04', 3, null, 4, 4),
('2025-10-05', 1, 5, null, 5);


-- drop database bdvenda
select * from nota;