/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemacompravenda;

import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author sandy
 */
public class CadNota extends javax.swing.JFrame {

    /**
     * Creates new form CadNota
     */
    public CadNota() {
        initComponents();
        Listar();
        preencherComboClientes();
        preencherComboProdutos();
        txtID.setEditable(false);
    }
    
    public void preencherComboFornecedores(){
        FornecedorDAO fDAO = new FornecedorDAO();
        List<Fornecedor> lista = fDAO.listarFornecedores();
        for(Fornecedor f: lista){
            cmbClienteFornecedor.addItem(f);
        }
    }
    public void preencherComboClientes(){
        ClienteDAO cDAO = new ClienteDAO();
        List<Cliente> lista = cDAO.listarClientes();
        for(Cliente c: lista){
            cmbClienteFornecedor.addItem(c);
        }
    }
    public void preencherComboProdutos(){
        ProdutoDAO pDAO = new ProdutoDAO();
        List<Produto> lista = pDAO.listaProdutos();
        for(Produto p: lista){
            cmbProduto.addItem(p);
        }
    }
    
    private void LimparForm(){
        txtID.setText("");
        txtData.setText("");
        txtQnt.setText("");
        cmbProduto.setSelectedIndex(0);
        cmbClienteFornecedor.setSelectedIndex(0);
    }
    
    private void Listar(){
        NotaDAO nDAO = new NotaDAO();
        List<Nota> nota = nDAO.listarNota();

        DefaultListModel<Nota> model = new DefaultListModel<>();
        nota.forEach((n) -> {
            model.addElement(n);
        });
        lstNota.setModel(model);
    }
    private void verificarEntradaSaida(){
        if(cmbEntradaSaida.getSelectedItem().toString().equals("Saída")){
            lblEntradaSaida.setText("Cliente:");
            cmbClienteFornecedor.removeAllItems();
            preencherComboClientes();
        }else{
            lblEntradaSaida.setText("Fornecedor:");
            cmbClienteFornecedor.removeAllItems();
            preencherComboFornecedores();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel23 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtQnt = new javax.swing.JTextField();
        txtData = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        cmbClienteFornecedor = new javax.swing.JComboBox();
        lblEntradaSaida = new javax.swing.JLabel();
        cmbProduto = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstNota = new javax.swing.JList<>();
        btnLimpar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        cmbEntradaSaida = new javax.swing.JComboBox<>();
        btnAtualizar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        menu = new javax.swing.JMenuBar();
        menuMenu = new javax.swing.JMenu();
        menuCliente = new javax.swing.JMenu();
        menuFornecedor = new javax.swing.JMenu();
        menuProduto = new javax.swing.JMenu();
        menuNota = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel23.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 48)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 153, 153));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Nota");

        txtID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Data:");

        jLabel17.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Quantidade:");

        txtQnt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtQnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQntActionPerformed(evt);
            }
        });

        txtData.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel24.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(102, 102, 102));
        jLabel24.setText("ID:");

        cmbClienteFornecedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblEntradaSaida.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        lblEntradaSaida.setForeground(new java.awt.Color(102, 102, 102));
        lblEntradaSaida.setText("Cliente:");

        cmbProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setText("Produto:");

        lstNota.setForeground(new java.awt.Color(102, 102, 102));
        lstNota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstNotaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstNota);

        btnLimpar.setBackground(new java.awt.Color(0, 153, 153));
        btnLimpar.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnLimpar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnSalvar.setBackground(new java.awt.Color(0, 153, 153));
        btnSalvar.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        cmbEntradaSaida.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbEntradaSaida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entrada", "Saída" }));
        cmbEntradaSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEntradaSaidaActionPerformed(evt);
            }
        });

        btnAtualizar.setBackground(new java.awt.Color(0, 153, 153));
        btnAtualizar.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnAtualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnExcluir.setBackground(new java.awt.Color(255, 153, 153));
        btnExcluir.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        menuMenu.setText("Menu");
        menuMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMenuMouseClicked(evt);
            }
        });
        menu.add(menuMenu);

        menuCliente.setText("Cliente");
        menuCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuClienteMouseClicked(evt);
            }
        });
        menu.add(menuCliente);

        menuFornecedor.setText("Fornecedor");
        menuFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuFornecedorMouseClicked(evt);
            }
        });
        menu.add(menuFornecedor);

        menuProduto.setText("Produto");
        menuProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuProdutoMouseClicked(evt);
            }
        });
        menu.add(menuProduto);

        menuNota.setText("Nota fiscal");
        menuNota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuNotaMouseClicked(evt);
            }
        });
        menu.add(menuNota);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblEntradaSaida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbClienteFornecedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAtualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(10, 10, 10)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQnt, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbEntradaSaida, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(txtQnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(cmbEntradaSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbClienteFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEntradaSaida)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtQntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQntActionPerformed

    private void lstNotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstNotaMouseClicked
         Nota n = lstNota.getSelectedValue();
        if (n != null) {
            txtID.setText(String.valueOf(n.getId()));
            txtData.setText(n.getData());
            txtQnt.setText(String.valueOf(n.getQuantidade()));
            
            Produto proCerto = null;
            for (int i = 0; i < cmbProduto.getItemCount(); i++) {
                Produto p = (Produto) cmbProduto.getItemAt(i);
                if (p.getId() == n.getFornecedorId()) {
                    proCerto = p;
                    break;
                }
            }
            if (proCerto != null) {
                cmbProduto.setSelectedItem(proCerto);
            }

            
            // --- Verifica se é nota de ENTRADA (tem fornecedor) ou SAÍDA (tem cliente) ---
            if (n.getFornecedorId() != 0) {
                cmbEntradaSaida.setSelectedItem("Entrada");
                preencherComboFornecedores(); // <-- recarrega o combo corretamente

                // Procura o fornecedor correspondente no combo
                for (int i = 0; i < cmbClienteFornecedor.getItemCount(); i++) {
                    Fornecedor f = (Fornecedor) cmbClienteFornecedor.getItemAt(i);
                    if (f.getId() == n.getFornecedorId()) {
                        cmbClienteFornecedor.setSelectedItem(f);
                        break;
                    }
                }
            } else if (n.getClienteId() != 0) {
                cmbEntradaSaida.setSelectedItem("Saída");
                preencherComboClientes(); // <-- recarrega o combo corretamente

                // Procura o cliente correspondente no combo
                for (int i = 0; i < cmbClienteFornecedor.getItemCount(); i++) {
                    Cliente c = (Cliente) cmbClienteFornecedor.getItemAt(i);
                    if (c.getId() == n.getClienteId()) {
                        cmbClienteFornecedor.setSelectedItem(c);
                        break;
                    }
                }
            }
        }
    }//GEN-LAST:event_lstNotaMouseClicked

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        LimparForm();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        Produto p = (Produto) cmbProduto.getSelectedItem();
        Nota n = new Nota();
        n.setData(txtData.getText());
        n.setQuantidade(Integer.parseInt(txtQnt.getText()));
        n.setProdutoId(p.getId());
        if(cmbEntradaSaida.getSelectedItem().equals("Saída")){
            Cliente c = (Cliente) cmbClienteFornecedor.getSelectedItem();
            n.setClienteId(c.getId());
            n.setFornecedorId(null);
            
        }else{
            Fornecedor f = (Fornecedor) cmbClienteFornecedor.getSelectedItem();
            n.setClienteId(null);
            n.setFornecedorId(f.getId());
        }
        NotaDAO nDAO = new NotaDAO();
        nDAO.inserirNota(n);
        LimparForm();
        Listar();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void menuMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMenuMouseClicked
        Menu tela = new Menu();
        tela.setVisible(true);
        tela.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_menuMenuMouseClicked

    private void menuClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuClienteMouseClicked
        CadCliente tela = new CadCliente();
        tela.setVisible(true);
        tela.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_menuClienteMouseClicked

    private void menuFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuFornecedorMouseClicked
        CadFornecedor tela = new CadFornecedor();
        tela.setVisible(true);
        tela.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_menuFornecedorMouseClicked

    private void menuProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuProdutoMouseClicked
        CadProduto tela = new CadProduto();
        tela.setVisible(true);
        tela.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_menuProdutoMouseClicked

    private void menuNotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuNotaMouseClicked
        CadNota tela = new CadNota();
        tela.setVisible(true);
        tela.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_menuNotaMouseClicked

    private void cmbEntradaSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEntradaSaidaActionPerformed
        verificarEntradaSaida();
    }//GEN-LAST:event_cmbEntradaSaidaActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        Produto p = (Produto) cmbProduto.getSelectedItem();
        Nota n = new Nota();
        n.setId(Integer.parseInt(txtID.getText()));
        n.setData(txtData.getText());
        n.setQuantidade(Integer.parseInt(txtQnt.getText()));
        n.setProdutoId(p.getId());
        if(cmbEntradaSaida.getSelectedItem().equals("Saída")){
            Cliente c = (Cliente) cmbClienteFornecedor.getSelectedItem();
            n.setClienteId(c.getId());
            n.setFornecedorId(null);
            
        }else{
            Fornecedor f = (Fornecedor) cmbClienteFornecedor.getSelectedItem();
            n.setClienteId(null);
            n.setFornecedorId(f.getId());
        }
        NotaDAO nDAO = new NotaDAO();
        nDAO.atualizarNota(n);
        LimparForm();
        Listar();
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int resposta = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir essa nota?",
            "Exclusão", JOptionPane.YES_NO_OPTION);
        if(resposta == JOptionPane.YES_OPTION){
            NotaDAO nDAO = new NotaDAO();
            nDAO.excluirNota(Integer.parseInt(txtID.getText()));
            JOptionPane.showMessageDialog(null, "Nota excluida!");
            LimparForm();
            Listar();
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadNota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox cmbClienteFornecedor;
    private javax.swing.JComboBox<String> cmbEntradaSaida;
    private javax.swing.JComboBox cmbProduto;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEntradaSaida;
    private javax.swing.JList<Nota> lstNota;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu menuCliente;
    private javax.swing.JMenu menuFornecedor;
    private javax.swing.JMenu menuMenu;
    private javax.swing.JMenu menuNota;
    private javax.swing.JMenu menuProduto;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtQnt;
    // End of variables declaration//GEN-END:variables
}
